export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS';
export const GET_USER_LOCATION_ERROR = 'GET_USER_LOCATION_ERROR';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
